### ISSUE TITLE
Toggle Light/Dark mode

### ISSUE THREAD

**Issue by Briy09** [x08d/222#2]
share another Bookmarklet:
```
javascript:(()=>{  script = document.createElement('script');  script.src = 'https://cdn.jsdelivr.net/npm/darkmode-js@1.3.4/lib/darkmode-js.min.js';  document.body.append(script);  const waitScriptLoad = window.setInterval(()=>{      if(typeof(Darkmode)==='function'){;          const darkmode = new Darkmode();          darkmode.toggle();          if(darkmode.isActivated()){            window.clearInterval(waitScriptLoad);          }      }  }, 500)})()
```

**Comment by x08d** [comment]
cool

**Comment by Briy09** [comment]
hi, @x08d  
what I mean is:
Can you add the Toggle Light/Dark mode feature to the [index.js](https://github.com/x08d/222/blob/master/index.js) ?
The final result is : Click the bookmark, the page turn into dark mode,and then click the bookmark again, the page turn into light mode, and then click the bookmark again, the page turn into dark mode……
